### ISSUE TITLE
Brainstorming Board for moving forward.

### ISSUE THREAD

**Issue by BeatLink** [LibreWolf-Browser/LibreWolf#1]
Okay, so here we can start laying out the things we need to do to move forward with this fork. I'll just start with a few on the top of my head.

* Rewrite the README to reflect the project's status as a completely independent non official fork that is neither endorsed by or related to Mozilla. https://github.com/librevixen/LibreVixen/issues/2
* Replace all relevant references to Firefox with LibreVixen. https://github.com/librevixen/LibreVixen/issues/3
* Find out how to compile Firefox with our own branding and implement the Modifications and Addons https://github.com/librevixen/LibreVixen/issues/6
* Begin work on a full featured release. https://github.com/librevixen/LibreVixen/issues/5

**Comment by brainscar** [comment]
Please add me to the org, thx

**Comment by brainscar** [comment]
Lets create a matrix chat room

**Comment by BeatLink** [comment]
> Please add me to the org, thx

Done!

> Lets create a matrix chat room

That is a great idea! Are you up for handling that?

**Comment by BeatLink** [comment]
So, status update. I've been figuring out how to compile Firefox. Implementing the modifications is the easiest of all, ironically. We just have to add the changes to the compiled browser before we package it. The real issue is branding. I've just about figured out how to use our own branding (its in the browser/branding) folder in the codebase. We can change the name, icons, default settings and other bits of data. I just have to figure out how to change the default profile location which is currently ~/.mozilla. It's creating conflicts with the existing install. Once we change that, we should be able to begin fine tuning the branding assets and start looking at packaging.

**Comment by BeatLink** [comment]
The initial build works! The name is changed, the executable, and it has its own config folder at ~/.librevixen ! I'll upload all the code tomorrow

**Comment by BeatLink** [comment]
Closing this page now. It's easier to track progress using individual issues
