### ISSUE TITLE
Compile without pocket

### ISSUE THREAD

**Issue by BeatLink** [LibreWolf-Browser/LibreWolf#13]

**Comment by FrostKnight** [comment]
Yeah... pocket is a security/privacy risk. So I would agree with you 100%. Ps, it looks like an interesting project! just don't let what happened to Initka happen to this project.

**Comment by BeatLink** [comment]
The current build uses Firefox's built in compile options to remove trademarking and branding. So if Mozilla has any issues with our build, it would be their issue. My only concern is the repo itself. It still has references to Firefox and still describes itself as a modification of firefox rather than a completely independent fork

**Comment by TheObserver6995** [comment]
> My only concern is the repo itself. It still has references to Firefox and still describes itself as a modification of firefox rather than a completely independent fork

Maybe it would help to reach out to firefox as soon as this has been changed, and ask them if everything is alright like this.

**Comment by BeatLink** [comment]
Is it good enough to disable it with the mozilla.cfg file?

**Comment by BeatLink** [comment]
Closing in preparation for move to gitlab
