### ISSUE TITLE
Issue: Not sure where to build

### ISSUE THREAD

**Issue by BeatLink** [LibreWolf-Browser/LibreWolf#15]
It seems that not many services can support building all of librevixen. Travis times out after about 50 minutes, Gitlab ci/cd times out after 3 hours. It seems the only way is for users to manually compile it

**Comment by shreyasminocha** [comment]
How long does it take to build librevixen?

**Comment by BeatLink** [comment]
More than 3 hours with CI/CD apparently

**Comment by FrostKnight** [comment]
Does anyone know how to apply patches onto firefox esr? and which version does the current script work on? (the alpha source code I mean...) 
Also, 
would be nice if it were just a fork without mozilla trademarks/bloat. Till you can adapt it the way mozilla does to be compatible with mozilla addons. 
Do you plan to change the folder it is put in? aka instead of being in a firefox folder, the folder would be called Librevixen... just a few thoughts.

**Comment by BeatLink** [comment]
> Does anyone know how to apply patches onto firefox esr? and which version does the current script work on? (the alpha source code I mean...)

I'm not sure about the ESR thing. The script in the repository compiles the latest nightly of firefox. 

> Also,
> would be nice if it were just a fork without mozilla trademarks/bloat. Till you can adapt it the way mozilla does to be compatible with mozilla addons.

Yeah. the script will compile it with our own branding and name. We still need a new icon, and some artwork for the about dialog. Since it is firefox nightly, with different brandings, Firefox addons should work normally, but i haven't tested as yet.

> Do you plan to change the folder it is put in? aka instead of being in a firefox folder, the folder would be called Librevixen... just a few thoughts.

Yes the final build will have its own user folder where all the profiles are stored. On linux, it's in ~/.librevixen


Right now, anyone can download this repo and compile a fully functional librevixen fork. The issue is, the compile process will install software and add files to your home folder (and possibly other places) so it would only be a good idea to compile it on another machine or in a VM. Right now, we're trying to find an online build system like travis or gitlab ci/cd, but one that has a long enough timeout for the script to run, since depending on the system, compiling may take several hours.

**Comment by BeatLink** [comment]
I think I have an idea. We could move to gitlab, and setup our own runners. Right now, ill be setting up a virtualbox install on my personal machine to run the builds with. If this works, then it would make sense to migrate to gitlab as well

**Comment by BeatLink** [comment]
It works! Things went a lot smoother using docker rather than virtualbox though. This is quite workable, for now.
