### ISSUE TITLE
Rename to LibreWolf?

### ISSUE THREAD

**Issue by BeatLink** [LibreWolf-Browser/LibreWolf#17]
What do you guys think about renaming to LibreWolf

**Comment by shreyasminocha** [comment]
I like it!

@Serkan-Devel

**Comment by BeatLink** [comment]
Awesome! And what do you think of this icon?

![path4789](https://user-images.githubusercontent.com/47278150/58620565-00630600-828d-11e9-9a84-303dc8093e46.png)

**Comment by shreyasminocha** [comment]
Could you try rotating it a bit more in the counter-clockwise direction? I feel it's too vertical at the moment.

**Comment by BeatLink** [comment]
ahh okay

**Comment by BeatLink** [comment]
![Librevixen svg](https://user-images.githubusercontent.com/47278150/58620803-98f98600-828d-11e9-8b26-70801ec8a981.png)

**Comment by BeatLink** [comment]
or how bout this?
![path875](https://user-images.githubusercontent.com/47278150/58621774-c2b3ac80-828f-11e9-87a3-51a4dfd61088.png)

**Comment by shreyasminocha** [comment]
I like the second one better. Maybe having a blue eye would make it more recognizable?

**Comment by BeatLink** [comment]
Yeah!

We should also remember to credit the author, Like this

Image by <a href="https://pixabay.com/users/OpenClipart-Vectors-30363/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=157677">OpenClipart-Vectors</a> from <a href="https://pixabay.com/?utm_source=link-attribution&amp;utm_medium=referral&amp;utm_campaign=image&amp;utm_content=157677">Pixabay</a>

**Comment by shreyasminocha** [comment]
What is its license?

**Comment by BeatLink** [comment]
Its free for commercial reuse https://pixabay.com/vectors/wild-wolf-howl-animal-black-157677/

**Comment by BeatLink** [comment]
![LibreWolf svg](https://user-images.githubusercontent.com/47278150/58622079-72891a00-8290-11e9-9ad3-756ddf62cd25.png)

**Comment by shreyasminocha** [comment]
![screenshot 2019-05-30 at 2 43 17 PM](https://user-images.githubusercontent.com/11537232/58622476-54033d00-82e9-11e9-833d-6acbd19b8748.jpg)

Do you like this eye better? Nailing the exact position is tough, but I think this is closer. And it being a polygon matches the rest of the image better imo. Maybe it could be a pentagon or a hexagon instead, but imo polygon > circle.

Let's also wait for others to weigh in on "LibreWolf" though.

**Comment by BeatLink** [comment]
yeah, i like this too

**Comment by Serkan-devel** [comment]
I'd take anything other than Librevixen.

Looks goid

**Comment by Serkan-devel** [comment]
I'd take anything other than Librevixen.

Looks good

**Comment by propeeves** [comment]
Libre implies FSF-approved to me. But probably not others, so LibreWolf seems good to me.

I like the icon without an eye, but with a filled-in icon I feel like white is the wrong colour.



> ![Librevixen svg](https://user-images.githubusercontent.com/47278150/58620803-98f98600-828d-11e9-8b26-70801ec8a981.png)

is probably my favourite design so far

**Comment by BeatLink** [comment]
How's this?

![LibreWolf svg](https://user-images.githubusercontent.com/47278150/58685580-db7c9a80-8341-11e9-857c-bc73e54cbda2.png)

**Comment by BeatLink** [comment]
Though, i too like the first image with only the outline, I dont think it scales well when reduced to the size of favicons and such

**Comment by SuperRobinHood** [comment]
Personally I prefer LibreVixen (of course, since I came up with it:D). Also hate the logo TBH. But name is not that important, let's get the packages ready! I have high hopes for this project but I can't into programming except webdev. If you guys get the packages ready I will recommend this browser on my website.

**Comment by SuperRobinHood** [comment]
Personally I prefer LibreVixen (of course, since I came up with it:D). Also hate the logo TBH. But name is not that important, let's get the packages ready! I have high hopes for this project but I can't into programming except webdev. If you guys get the packages ready I will recommend this browser on my website.

**Comment by b16r05** [comment]
My input... I love the first icon; no tooth and no eye! It is very simple and can probably appear nice as an icon and favicon. Probably the cartoony feel makes it appealing : )

**Comment by b16r05** [comment]
> 
> 
> Though, i too like the first image with only the outline, I dont think it scales well when reduced to the size of favicons and such

I actually thought it would scale well because of the thin outline... but it looks like a crooked mountain, LOL! The images with fat outline looks better in small size.

**Comment by BeatLink** [comment]
hahahaha yeah, I understand :)

**Comment by BeatLink** [comment]
Hey guys, I'm designing the logo now! Let me know which of these you like

![Logo svg](https://user-images.githubusercontent.com/47278150/59043126-4bf35200-8841-11e9-8332-e84f8e32c0f1.png)



![Logo svg](https://user-images.githubusercontent.com/47278150/59043142-531a6000-8841-11e9-95c1-cb9f20c71c18.png)

**Comment by BeatLink** [comment]
In the meantime, ill change the README to the first

**Comment by SuperRobinHood** [comment]
If we're sticking with the wolf logo, my shitty artistic sense tells me the eye should be a little lower, like in shreyasminocha's black logo.

**Comment by BeatLink** [comment]
Hmm, I'll take a look again!

And a little note to myself, remember to credit the author, Like this

Image by OpenClipart-Vectors from Pixabay

**Comment by BeatLink** [comment]
I think the rename is just about complete. Closing the issue
