### ISSUE TITLE
Support for ALSA and sndio

### ISSUE THREAD

**Issue by BeatLink** [LibreWolf-Browser/LibreWolf#19]
Just a quick question, can this fork also support alsa and sndio?

I don't like the idea of using pulseaudio and sndio is used by a lot of BSD operating systems. As for alsa, well I just am using it till sndio migration is completed in my linux distro.  ;)

_Originally posted by @FrostKnight in https://github.com/LibreWolf-Browser/LibreWolf/issues/6#issuecomment-499694655_

**Comment by BeatLink** [comment]
Though I'm not entirely sure how one would go about implementing support, I don't see why we couldn't. It would be quite a ways in the future however, as the primary concern right now is building and packaging the browser itself and completing the rebranding, and getting basic functionality online. But who knows? Maybe others could open a merge request

**Comment by SuperRobinHood** [comment]
Apparently all the ALSA code is still inside firefox, just needs --enable-alsa during build.

**Comment by BeatLink** [comment]
huh, will do!

**Comment by FrostKnight** [comment]
Cool, thanks for making this request!  :)

btw, can the folder that it is put in be something besides firefox? can you make the default folder in .mozilla, librewolf?
If possible, I mean. :)

**Comment by BeatLink** [comment]
Thats the main plan, and the main reason we needed a full compile. Right now, the default folder will be .librewolf

**Comment by BeatLink** [comment]
Closing in preparation for move to gitlab
