### ISSUE TITLE
Difference between LibreWolf and Waterfox?

### ISSUE THREAD

**Issue by BeatLink** [LibreWolf-Browser/LibreWolf#22]
It seems that LibreWolf has many of the same goals as WaterFox, namely promoting privacy, security and user freedom. Is there any reason we couldn't work with them rather than having our own independent fork?

**Comment by BeatLink** [comment]
Also, even if there are reasons to keep our own independent fork (say, we have some functionality or settings that waterfox wishes not to implement) wouldn't it be better to base LibreWolf on Waterfox rather than the base Firefox build?

**Comment by SuperRobinHood** [comment]
Even though waterfox might give the impression of having similar goals, it is an illusion: https://spyware.neocities.org/articles/waterfox.html. Pale Moon outclasses Waterfox anyway. LibreWolf should carve its niche by being the "ungoogled-firefox". So let's keep the FF base.

**Comment by BeatLink** [comment]
Got it
