### ISSUE TITLE
Diversify collaborators

### ISSUE THREAD

**Issue by shreyasminocha** [LibreWolf-Browser/LibreWolf#24]
Part of the reason Librefox met the fate that it did was that only intika had access to the repo. While I don't expect @BeatLink to similarly disappear, I feel it's best for the future of the project if there are other people who have access to the organisation and the repo. This is not to mention that they would also have access to triaging and pull request reviewing and could help with the overall maintenance of the project. 

Perhaps it's too early for this and @BeatLink could add people who show interest in and make significant contributions to the project in the months to come.

**Comment by BeatLink** [comment]
I absolutely agree, I don't want to be the only one working on this. It should be a community run project, in both collaboration and in decisions and governance.

**Comment by shreyasminocha** [comment]
Thanks for taking steps in this direction.
