### ISSUE TITLE
Input on privacy decisions and the goal of LibreWolf

### ISSUE THREAD

**Issue by BeatLink** [LibreWolf-Browser/LibreWolf#25]
Now is as good a time as any to discuss and decide on the choices we will make for LibreWolf, and its goals as a web browser. 

I was thinking that we should honour its roots as a set of patches to maximize security and privacy, and to be the ungoogled-chromium equivalent of Firefox. 

So a few things are pretty clear:
* We will not compile librewolf with any telemetry, health reporting or data gathering functionality.
* We will compile librewolf without pocket (as it is closed source and available as an addon)
* For now, we will implement the original patches of this project (and all the settings within). Advanced users can change these post install and we can review these later.

Some decisions that are not so clear:
* Should we compile with DRM, Autofill and WebRTC? (These features are often used and may be a deal breaker to new users)

**Comment by BeatLink** [comment]
Solving some of these concerns could be a good start https://spyware.neocities.org/articles/firefox.html

**Comment by SuperRobinHood** [comment]
In regards to search engines, what I'd personally do is to include all the ones that are private BY DEFAULT. Then the user can choose from those or install an un-private one if he wants to. Installing search engines is kind of a hassle in firefox (you need a plugin from mycroftproject) so it'd be nice to have them included by default. My specific recommendations:

StartPage
DuckDuckGo
DuckDuckGo Images
SearX
Jive Search (lesser known but really like the results from it - which it gets from yandex)
Qwant
MetaGer
Invidio.us (de-googled youtube)

Having no search engine by default would be a usability disaster, I don't recommend it at all if we're to become a real alternative to FF.

**Comment by shreyasminocha** [comment]
I think we should compile with DRM and WebRTC, but these should be disabled by default.
I agree with @SuperRobinHood about search engines. I personally prefer DuckDuckGo, but that's a choice I make. I think the default list of search engines should only include "privacy-conscious" search engines (it may be easier to eliminate search engines that are not privacy-conscious). Perhaps we could ask the user to set a default while setting the browser up (the one-time setup screen may or may not be a good idea…).

**Comment by BeatLink** [comment]
Okay, so I will compile firefox normally, using the compile scripts to only add the branding. All the privacy and security modifications will be made by the policies file and the cfg file. Sounds good?

**Comment by BeatLink** [comment]
Closing in preparation for move to gitlab
