### ISSUE TITLE
Full Release of project.

### ISSUE THREAD

**Issue by BeatLink** [LibreWolf-Browser/LibreWolf#5]
This is where we will discuss and plan the full release of the project as an independent application

Platforms that we could support
* DEBs
* RPMs
* Flatpak
* AppImages

I think we should focus on Flatpak and AppImages since they're easier to maintain especially for the group's small size, and they're universal across distributions

**Comment by Araly** [comment]
I could research how to make that an AUR package too, if that's interesting

**Comment by brainscar** [comment]
+1 for appimage

**Comment by SuperRobinHood** [comment]
How about Slackware (.txz)? Well rpm2tgz can convert but it would still be nice.

Anyway, great to see the project get going!

**Comment by b16r05** [comment]
Not to add to the workload, but I thought snap would also be included... considering how popular Ubuntu and Ubuntu-based distros are.

**Comment by BeatLink** [comment]
> Not to add to the workload, but I thought snap would also be included... considering how popular Ubuntu and Ubuntu-based distros are.

Well, Ubuntu supports flatpak, which is why I did not think of snaps.

**Comment by FrostKnight** [comment]
Make it possible to compile from source and if possible, take out the requirement for electron. ps, is this browser going to be 100% Free software? I would love to see that happen. :) 
Snap is crap, but all the other options sound good including source code install. :)

**Comment by FrostKnight** [comment]
Oh one last thing, will you support new addons for flibrevixen, such as noscript, httpseverywhere and ublock origin/nano adblocker? I would like to see full webextension support if possible. :)

**Comment by FrostKnight** [comment]
Will librevixen have full support for webextensions firefox addons? Such as noscript, nanoadblocker/ublock origin and privacy possum, etc... 
:)

**Comment by b16r05** [comment]
Probably the focus now should be re-brand, update to latest FF code base and release. Addons... from the way things were going earlier, to make them redundant and include privacy ones directly built-into the browser... sounds like a lot of work (almost a project in itself... LOL!

**Comment by SuperRobinHood** [comment]
@b16r05 I agree - need to get the packages out ASAP. Then we can advertise it and hopefully get some people to help out.

**Comment by BeatLink** [comment]
> ps, is this browser going to be 100% Free software? I would love to see that happen. :)

I would love to see that happen. The build I made already disabled DRM. 

> Will librevixen have full support for webextensions firefox addons? Such as noscript, nanoadblocker/ublock origin and privacy possum, etc...

Its built from Firefox Nightly, so it already does!

**Comment by BeatLink** [comment]
So right now, there is a script that can build librevixen here https://github.com/librevixen/LibreVixen/tree/master/librevixen_browser

**Comment by BeatLink** [comment]
Okay, so I've had some success with the gitlab runner using my personal device, however I've been hampered by internet issues and the long compile time (which means its often hours into the compile before i find an issue). However, once we can demonstrate this actually working, then we can move to gitlab and set this up proper

**Comment by BeatLink** [comment]
I give you: the first ever release of librewolf!

https://github.com/LibreWolf-Browser/LibreWolf/releases/tag/v0.0.0-alpha

**Comment by BeatLink** [comment]
Closing in preparation for move to gitlab
