### ISSUE TITLE
Creating a Firefox fork with the modifications built in

### ISSUE THREAD

**Issue by BeatLink** [LibreWolf-Browser/LibreWolf#6]

**Comment by brainscar** [comment]
This raises a good point, are we going to ship a librevixen complete build or just config files/a script?

**Comment by BeatLink** [comment]
We will ship a complete build. That way, it shouldn't affect any existing Firefox installation, plus it is more detached from Firefox itself, resulting in less legal issues. The good news we won't have to fork and manage an entire codebase. All we need to do, is download the original Firefox source, swap in our own branding, compile, then add in the configuration files, custom preferences and scripts. Right now, I'm fine tuning a script to do just that!

**Comment by FrostKnight** [comment]
Just a quick question, can this fork also support alsa and sndio?

I don't like the idea of using pulseaudio and sndio is used by a lot of BSD operating systems. As for alsa, well I just am using it till sndio migration is completed in my linux distro.  ;)

**Comment by BeatLink** [comment]
Though I'm not entirely sure how one would go about implementing support, I don't see why we couldn't. It would be quite a ways in the future however,  as the primary concern right now is building and packaging the browser itself and completing the rebranding, and getting basic functionality online. But who knows? Maybe others could open a merge request

**Comment by BeatLink** [comment]
Merging this with issue #5
